services:
  sql-assistant:
    image: sql-assistant:latest
    container_name: sql-assistant-app
    # ports:
    #   - "18028:5000"
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - DATABASE_URL=mysql://A_APP_ISA:Tlsfkdlvm0701!@10.172.33.140:19001/sql_assistant

      # SQL ASSISTANT API KEY Setting
      - AI_API_BASE_URL=http://10.172.33.161:18020/v1/chat-messages
      - SQL_ASSISTANT_API_KEY_SQL_EXPLANATION=app-A7SwTtuSRCjcd9FKy7knOygF
      - SQL_ASSISTANT_API_KEY_SQL_GRAMMAR=app-Cu9GVFRLHL36K8urqbIJKqi5
      - SQL_ASSISTANT_API_KEY_SQL_COMMENT=app-nDvxBkojarVUnAnY9mCJFMzw
      - SQL_ASSISTANT_API_KEY_SQL_TRANSFORMATION=app-FtuiuxFKVfMQOTykoTkHz68e
      - SQL_ASSISTANT_API_KEY_SQL_CREATION=app-MKiOOiO6IJtb3atcWOXtEfN8
      
      # 애플리케이션이 사용할 포트를 환경 변수로 전달
      - PORT=18027

      - TZ=Asia/Seoul
    restart: unless-stopped
    network_mode: "host" 